### ISSUE TITLE
qm not working 

### ISSUE THREAD

**Issue by karen33** [biocatiit/musclex#12]
the following error happened when I do the set manual center and rotation. \
Please report the problem with error message below and the input image

Image : pwmhc2day2-3.tif

Error : <type 'exceptions.IOError'>

Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/musclex/ui/QuadrantFoldingGUI.py", line 1764, in processImage
self.quadFold.process(flags)
File "/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py", line 133, in process
self.cacheInfo()
File "/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py", line 85, in cacheInfo
pickle.dump(self.info, open(cache_file, "wb"))
IOError: [Errno 13] Permission denied: '/home/karen/20140405Hsu/pwmhc2/pwmhc2_tifave/qf_cache/pwmhc2day2-3.tif.info'

another error message when I did set manual rotation. 

Please report the problem with error message below and the input image

Image : pwmhc2day2-3.tif

Error : <type 'exceptions.IOError'>

Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/musclex/ui/QuadrantFoldingGUI.py", line 1764, in processImage
self.quadFold.process(flags)
File "/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py", line 133, in process
self.cacheInfo()
File "/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py", line 85, in cacheInfo
pickle.dump(self.info, open(cache_file, "wb"))
IOError: [Errno 13] Permission denied: '/home/karen/20140405Hsu/pwmhc2/pwmhc2_tifave/qf_cache/pwmhc2day2-3.tif.info'

I updated musclex today in 2/23/2018 and the software should be new. I attached the image I used for analyzing. It's a tif file. not sure if that cause problem. 

[pwmhc2day2-4.zip](https://github.com/biocatiit/musclex/files/1753473/pwmhc2day2-4.zip)

**Comment by karen33** [comment]
I found out the problem might happened from my image were from merging images. I will redo the image merge.

**Comment by jiranun** [comment]
Hi Karen,

It seems like the problem was the program couldn’t read cache file because permission denied. If it happens again, please delete folder qf_cache under your data folder, the re-process the image again.

Let me know if the problem still exists.

Thanks
