### ISSUE TITLE
Problem with newly install muscle x

### ISSUE THREAD

**Issue by ChenChingYuanVicky** [biocatiit/musclex#17]
Hi ; I try to install new update from musclex and use eq function. The software showed me the error code
vicky@HAMM54:~$ musclex eq
Traceback (most recent call last):
  File "/usr/local/bin/musclex", line 7, in <module>
    from musclex.main import main
  File "/usr/local/lib/python2.7/dist-packages/musclex/main.py", line 32, in <module>
    from musclex.ui.pyqt_utils import *
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/pyqt_utils.py", line 35, in <module>
    from PyQt5.QtCore import *
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class
vicky@HAMM54:~$

**Comment by XintianLee** [comment]
Hi,

This error does seem a little confusing. The program will first try to import PyQt4 modules and then the PyQt5 if the former fails. You got this error because PyQt4.QtCore was imported successfully but PyQt4.Gui or other PyQt4 modules failed to be imported.
Probably, you have both PyQt4 and PyQt5 installed but PyQt4 does not work properly. To test this, open a python console and try running following lines:
```python
from PyQt4.QtCore import *
from PyQt4.QtGui import *
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg as FigureCanvas
```
If an error occurs, you'll need to deal with that one first.

Thanks,
Xintian
