### ISSUE TITLE
Problem with musclex update

### ISSUE THREAD

**Issue by SageMay** [biocatiit/musclex#18]
Resolved dependency on msgpack on local computer. 
Local computer running mac osx el capitan 10.11.6
Using pip install

When trying to opening equator function: 

D-10-19-225-39:~ Danielabmaster$ musclex eq
/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

  from ._conv import register_converters as _register_converters

D-10-19-225-39:~ Danielabmaster$ osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.

button returned:OK

**Comment by XintianLee** [comment]
Hi,
According to the description in your error log:
```
Traceback (most recent call last):
  File "/Users/Danielabmaster/anaconda3/bin/musclex", line 11, in <module>
    sys.exit(main())
  File "/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/musclex/main.py", line 47, in main
    from musclex.ui.EQStartWindow import EQStartWindow
  File "/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/musclex/ui/EQStartWindow.py", line 35, in <module>
    from ..ui.EquatorWindow import EquatorWindow
  File "/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/musclex/ui/EquatorWindow.py", line 37, in <module>
    from ..CalibrationSettings import CalibrationSettings
  File "/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/musclex/CalibrationSettings/__init__.py", line 28, in <module>
    from .CalibrationSettings import CalibrationSettings
  File "/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/musclex/CalibrationSettings/CalibrationSettings.py", line 37, in <module>
    from ..utils.image_processor import *
  File "/Users/Danielabmaster/anaconda3/lib/python3.6/site-packages/musclex/utils/image_processor.py", line 29, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```
OpenCV is not installed. To install OpenCV by pip, you can run
```
sudo pip install opencv-python
```
You may also need to install other dependencies besides OpenCV. See our [installation guide](https://musclex.readthedocs.io/en/latest/Installation/pip.html).

Hope this helps.
Xintian

**Comment by SageMay** [comment]
Thanks, the directions were helpful, and I got it running (so excited!)!
For reference, I had to install msgpack too, which I don't see listed on
the install directions. Maybe most users have this.
