### ISSUE TITLE
QF program is broken

### ISSUE THREAD

**Issue by WeikangMa** [biocatiit/musclex#35]
Here is the error message:
weikang@bearshark:~$ musclex qf
Traceback (most recent call last):
  File "/usr/local/bin/musclex", line 11, in <module>
    load_entry_point('musclex==1.14.1', 'console_scripts', 'musclex')()
  File "/usr/local/lib/python2.7/dist-packages/musclex/main.py", line 52, in main
    from musclex.ui.QuadrantFoldingGUI import QuadrantFoldingGUI
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/QuadrantFoldingGUI.py", line 36, in <module>
    from ..modules.QuadrantFolder import QuadrantFolder
  File "/usr/local/lib/python2.7/dist-packages/musclex/modules/QuadrantFolder.py", line 41, in <module>
    import ccp13
ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

PS: In the PT program, the output data and the column headers are not 1-1 coresponding

**Comment by XintianLee** [comment]
The problem is about importing musclex-ccp13. And from the error message, `libgfortran.so.3` can not be found. So probably you need to install **gfortran** on your Linux.
```
sudo apt-get install gfortran
```
