### ISSUE TITLE
pt box issues

### ISSUE THREAD

**Issue by rmadhura-iit** [biocatiit/musclex#37]
Getting this error message when trying to add peaks within a box on musclex-pt. I tried adding multiple boxes and selecting peaks within each box, but still getting the same issue. From what I understand, it could be an axis mapping issue. 

![image](https://user-images.githubusercontent.com/43549103/51628529-d9757b80-1f0a-11e9-9d89-10c18476544b.png)

**Comment by rmadhura-iit** [comment]
More information on the error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 387, in process
    proxy(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/musclex/ui/ProjectionBoxTab.py", line 505, in graphOnMotion2
    "Distance = " + str(round(distance, 3)) + ", Intensity = " + str(hist[int(round(x))]))
IndexError: index 19 is out of bounds for axis 0 with size 19


Source file: https://drive.google.com/open?id=13INi3E334v-B4SHfb5PJb2K0YP5QEx-p
