### ISSUE TITLE
MuscleX won't start up on MacOS

### ISSUE THREAD

**Issue by gpfarman** [biocatiit/musclex#68]
Trying to use Muscle X to do quadrant folding but when I start the program and run the Quadrant Folding routine the system kicks back this error.

Traceback (most recent call last):
  File "site-packages/pyopencl/tools.py", line 95, in first_arg_dependent_memoize
KeyError: <pyopencl.Context at 0x7fc61ce1d530 on <pyopencl.Device 'Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz' on 'Apple' at 0xffffffff>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "musclex/main.py", line 142, in <module>
  File "musclex/main.py", line 55, in main
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "musclex/ui/QuadrantFoldingGUI.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "musclex/utils/image_processor.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyFAI/__init__.py", line 57, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyFAI/azimuthalIntegrator.py", line 112, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyFAI/opencl/__init__.py", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "site-packages/pyFAI/opencl/common.py", line 272, in <module>
  File "site-packages/pyFAI/opencl/common.py", line 315, in OpenCL
  File "site-packages/pyFAI/opencl/common.py", line 240, in _measure_workgroup_size
  File "site-packages/pyopencl/array.py", line 929, in __add__
  File "site-packages/pyopencl/array.py", line 137, in kernel_runner
  File "site-packages/pyopencl/array.py", line 747, in _axpbz
  File "<decorator-gen-12>", line 2, in get_axpbz_kernel
  File "site-packages/pyopencl/tools.py", line 98, in first_arg_dependent_memoize
  File "site-packages/pyopencl/elementwise.py", line 648, in get_axpbz_kernel
  File "site-packages/pyopencl/elementwise.py", line 178, in get_elwise_kernel
  File "site-packages/pyopencl/elementwise.py", line 161, in get_elwise_kernel_and_types
  File "site-packages/pyopencl/elementwise.py", line 111, in get_elwise_program
  File "site-packages/pyopencl/__init__.py", line 462, in build
  File "site-packages/pyopencl/__init__.py", line 506, in _build_and_catch_errors
pyopencl.cffi_cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - 

Build on <pyopencl.Device 'Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz' on 'Apple' at 0xffffffff>:

(options: -I /Applications/MuscleX.app/Contents/MacOS/pyopencl/cl)
(source saved as /var/folders/fv/7hpmcb2x0h73jtlj5mccm0300000gn/T/tmpq8edkzj4.cl)

**Comment by Julesnab** [comment]
Closed as it should be fixed by the latest updates.
